apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  FLASK_DEBUG: "false"

  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_NAME: "cloud"

  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "vvardhan2211@gmail.com"
  MAIL_PASSWORD: "czvk tjjz kiea qrbu"